/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewChinh;

//import dao.CancelBillDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import model.Bill;
//import model.PenaltyBill;

/**
 *
 * @author hongd
 */
public class VePhatFrm extends javax.swing.JFrame {

    /**
     * Creates new form ShowPenaltyBillFrm
     */
    
//    private CancelBillDAO cancelBillDAO;
//    
//    private DefaultTableModel tm;
//    
//    private PenaltyBill penaltyBill;
    
    public VePhatFrm(HuyVeFrm huyve) {
        initComponents();
        setLocationRelativeTo(this);
//        txtRuleCancelBill.setEditable(false);
//        cancelBillDAO = new CancelBillDAO();
//        String[] cols = {"id bill", "name tour", "depature" ,"destination", "start date", "name customer", "id card number", "id card type", "address", "phone number", "email", "customer amount", "price", "fine money"};
//        tm = new DefaultTableModel(cols, 0);
//        
//        tblPenaltyBill.setModel(tm);
//        
//        penaltyBill = cancelBillDAO.getPenaltyBill(bill);
//        
//        showPenaltyBill();
        
    }

//    public ShowPenaltyBillFrm1() {
//        initComponents();
//    }
//    
//    
//    
//    private void showPenaltyBill(){
//        tm.setRowCount(0);
//        if(penaltyBill != null)
//            tm.addRow(penaltyBill.toObjects());
//    }
//    
//    void showMessage(String message) {
//        JOptionPane.showMessageDialog(this, message);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenaltyBill = new javax.swing.JTable();
        btnConfirmCancelBill = new javax.swing.JButton();
        txtRuleCancelBill = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Vé phạt");

        tblPenaltyBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id hóa đơn", "Tour", "Nơi đi", "Nơi đến", "Ngày đi", "Tên khách", "Số Id", "Loại Id", "Số ĐT", "Email", "Địa chỉ", "Số khách", "Giá", "Tiền phạt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPenaltyBill);

        btnConfirmCancelBill.setText("Confirm");
        btnConfirmCancelBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmCancelBillActionPerformed(evt);
            }
        });

        txtRuleCancelBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuleCancelBillActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Lý do");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmCancelBill)
                .addGap(481, 481, 481))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 566, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(457, 457, 457))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtRuleCancelBill)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuleCancelBill, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnConfirmCancelBill)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmCancelBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmCancelBillActionPerformed
        // TODO add your handling code here:
//        try {
//            if(penaltyBill == null){
//                return;
//            }
//            boolean res = cancelBillDAO.deleteBill(penaltyBill.getBill());
//            if(res == true){
//                showMessage("Huy ve thanh cong");
//                
//            }else{
//                showMessage("Huy ve khong thanh cong");
//            }
//            new EmployeeHomeFrm().setVisible(true);
//            this.dispose();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_btnConfirmCancelBillActionPerformed

    private void txtRuleCancelBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuleCancelBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuleCancelBillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmCancelBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPenaltyBill;
    private javax.swing.JTextField txtRuleCancelBill;
    // End of variables declaration//GEN-END:variables
}
